spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/studyping
#    username: root
#    password: haechan8864
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # ?? ?? update, ???? validate ?? none # update -> validate 로 변경
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # UTF-8 ?? (??)
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # ???? ????? (??)
  jackson:
    time-zone: Asia/Seoul

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

server:
  port: 8080

jwt:
#studypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstoken
  secretKey: c3R1ZHlwaW5nYWNjZXNzdG9rZW5zdHVkeXBpbmdhY2Nlc3N0b2tlbnN0dWR5cGluZ2FjY2Vzc3Rva2Vuc3R1ZHlwaW5nYWNjZXNzdG9rZW5zdHVkeXBpbmdhY2Nlc3N0b2tlbnN0dWR5cGluZ2FjY2Vzc3Rva2Vuc3R1ZHlwaW5nYWNjZXNzdG9rZW4=
  expiration: 3000

logging:
  level:
    org:
      springframework:
        security: DEBUG # Spring Security ??? ??? ???