spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ?? update, ???? validate ?? none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # UTF-8 ?? (??)
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # ???? ????? (??)
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080

jwt:
#studypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstokenstudypingaccesstoken
  secretKey: c3R1ZHlwaW5nYWNjZXNzdG9rZW5zdHVkeXBpbmdhY2Nlc3N0b2tlbnN0dWR5cGluZ2FjY2Vzc3Rva2Vuc3R1ZHlwaW5nYWNjZXNzdG9rZW5zdHVkeXBpbmdhY2Nlc3N0b2tlbnN0dWR5cGluZ2FjY2Vzc3Rva2Vuc3R1ZHlwaW5nYWNjZXNzdG9rZW4=
  expiration: 3000